<a href="https://colab.research.google.com/github/kyrax-sys/machineLearning_Lab/blob/main/lab01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [25]:
#activity1_numpy
import numpy as np



In [5]:
a=np.array([10,20,30,40])

In [6]:
print(a)

[10 20 30 40]


In [8]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])

In [9]:
print(a+b)
print(a-b)
print(a*b)

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]


In [12]:
q = np.array([5.2, 4.1, -2.3, 15.5, 18.2, 16.0])
print(np.mean(q))
print(np.median(q))

9.450000000000001
10.35


In [13]:
print(np.max(q))
print(np.min(q))

18.2
-2.3


In [26]:
#activity2_nump_manipal_temp
days = np.arange(1, 32)

temps = np.array([
    27, 27, 28, 28, 28, 28, 28,
    28, 28, 28, 28, 29, 28, 28,
    28, 28, 27, 28, 28, 28, 28,
    28, 29, 29, 29, 30, 29, 29,
    28, 28, 29
])

In [27]:
hot = np.max(temps)
cold = np.min(temps)

print(f"hottest temp: {hot}°C")
print(f"coldest temp: {cold}°C")

hottest temp: 30°C
coldest temp: 27°C


In [28]:

heat = temps >= 35
hot_days = days[heat]
print("days with temp >= 35°C:", hot_days if len(hot_days) else "not found")

print(f"average temperature: {np.mean(temps)}°C")

days with temp >= 35°C: not found
average temperature: 28.193548387096776°C
